apiVersion: v1
kind: Pod
metadata:
 name: health2
 labels:
  app: v1.0.0
spec:
 containers:
  - name: httpget
    image: registry.k8s.io/e2e-test-images/agnhost:2.40
    args:
     - liveness
    livenessProbe:
     httpGet:
      path: /healthz
      port: 8080
      httpHeaders:
       - name: Custome-Header
         value: Awesome
     initialDelaySeconds: 10
     periodSeconds: 5
