apiVersion: v1
kind: Pod
metadata:
 name: health2
 labels:
  app: v1
spec:
 containers:
  - name: health2
    image: registry.k8s.io/e2e-test-images/agnhost:2.40
    imagePullPolicy: IfNotPresent
    args:
     - liveness
    livenessProbe:
     httpGet:
      path: /healthz
      port: 8080
      httpHeaders:
       - name: Custom-Header
         value: Awesome
     initialDelaySeconds: 10
     periodSeconds: 5
